spring.application.name=Scorebound

spring.datasource.url=${SCOREBOUND_DB_URL:jdbc:postgresql://localhost:5432/scorebound}
spring.datasource.username=${SCOREBOUND_DB_USERNAME:scorebound}
spring.datasource.password=${SCOREBOUND_DB_PASSWORD:scorebound}

management.endpoints.web.exposure.include=health,info
